post http://localhost:5000/createuser
Content-Type: application/json

{
    "username": "superadmin",
    "password": "12345",
    "confpassword": "12345",
    "role": "superadmin"
}

###
post http://localhost:5000/createuser
Content-Type: application/json

{
    "username": "admin",
    "password": "12345",
    "confpassword": "12345",
    "role": "admin",
    "cabanguuid": "197fa82d-bd4b-4c6d-92f1-21b875cdd3d7"
}

###
put http://localhost:5000/updateuser/67a1852a-72ec-42a5-acc8-49f4a1bb10e0
Content-Type: application/json

{
    "username": "hapuscabang",
    "password": "12345",
    "confpassword": "12345",
    "role": "kasir",
    "cabanguuid": "1aeceb73-2960-49b2-8eb4-c00139ddfe11"

}

###
post http://localhost:5000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "12345"
}
###
post http://localhost:5000/login
Content-Type: application/json

{
    "username": "superadmin",
    "password": "12345"
}
###
post http://192.168.100.18:5000/login
Content-Type: application/json

{
    "username": "kasir",
    "password": "12345"
}

###
post http://localhost:5000/login
Content-Type: application/json

{
    "username": "hapuscabang",
    "password": "12345"
}




###
post http://localhost:5000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "12345"
}


###
get http://192.168.100.18:5000/me

###
delete http://localhost:5000/logout


###
delete http://localhost:5000/deletecabang/d93ef91c-6be9-492f-bf24-5083d31f24a9
###
post http://localhost:5000/createcabang
Content-Type: application/json

{
    "namacabang":"cabang2",
    "alamat":"jl.baru",
    "latitude":"-7.003011",
    "longitude":"110.411597"
}

###
get http://localhost:5000/cabang


###
get http://192.168.100.18:5000/kategori


###
delete http://192.168.100.18:5000/deletekategori/37a3702c-db6d-456b-9a5e-01fd1a10bb57

###
post http://localhost:5000/createkategori
Content-Type: application/json

{
    "namakategori": "makanan"

}

###
post http://localhost:5000/createbarang
Content-Type: application/json

{
    "namabarang": "Barang Baru",
    "harga": 100000,
    "kategoriuuid": "8dfc2e1d-31b1-47f0-a38d-96d771669128",
    "foto": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABYklEQVQ4y6XTv0oDQRSH8c+OAgZgiCFhGhIixMSLkFDCx9AzJjFTEQu0kEWlNsLFEmFxRRHF0EA5iYRSIix+E/EMjFNpslFk1mYkL3jzH9znLusouId1bzSSfTWBf4lbUReU8XK8QTVIV4rj6k0tbSGSLTwkMdCRicrjjzXWsi5J+gQ/zJrZBhS/w8UB5FtrhvNiLRtAriVqUInXLiiXwPkvR2vMRBhnxRgeEb3skz6hTgrBqxDtAsL3HKOgbD6g41LeSo9AjrVvCtnEuORvjiOJSZ5L1RC+iWA3gZqqSXXETQSOpsDWVjNz2F16uERlvhKoMogH2m5mEqa7kTGyjO9NsV4kDpYuYrOm2zZetKhGg1LvqMKf60PntIBrl/wAZID08G8+AyAAAAAElFTkSuQmCC"
}

###
get http://localhost:5000/barang

###
post http://localhost:5000/createtransaksi
Content-Type: application/json

{
  
  "pembayaran": "cash",
  "items": [
    {
      "baranguuid": "0dca2395-7e4e-437f-a46f-976d67691a43",
      "jumlahbarang": 5
    },
    {
      "baranguuid": "102562db-14be-418b-b6c4-e4bd62c65549",
      "jumlahbarang": 5
    }
  ]
}

###
post http://localhost:5000/createtransaksi
Content-Type: application/json

{
  "pembayaran": "qris",
  "items": [
    {
      "baranguuid": "0dca2395-7e4e-437f-a46f-976d67691a43",
      "jumlahbarang": 1
    },
    {
      "baranguuid": "102562db-14be-418b-b6c4-e4bd62c65549",
      "jumlahbarang": 1
    }
  ]
}

###
post http://localhost:5000/createtransaksi
Content-Type: application/json

{
  "pembayaran": "cash",
  "items": [
    {
      "baranguuid": "0dca2395-7e4e-437f-a46f-976d67691a43",
      "jumlahbarang": 20
    }
  ]
}

###
put http://localhost:5000/updatetransaksi/02008ce6-aaab-4335-bed4-ee1e287e6aa8
Content-Type: application/json

{
  
  "pembayaran": "cash",
  "items": [
    {
      "baranguuid": "0dca2395-7e4e-437f-a46f-976d67691a43",
      "jumlahbarang": 5
    },
    {
      "baranguuid": "102562db-14be-418b-b6c4-e4bd62c65549",
      "jumlahbarang": 9
    }
  ]
}

###
get http://localhost:5000/getuser

###
get http://localhost:5000/laporan?month=2024-12

###
get http://192.168.100.18:5000/chartlaporan
###
get http://localhost:5000/laporandetail


//api for superadmin
###
get http://localhost:5000/transaksi/226c33b1-97cc-48d7-b35b-954d339afacc

//api for superadmin(allcabang)
###
get http://localhost:5000/gettransaksi

//api for rekap user
###
get http://localhost:5000/gettransaksiuser

//transaksicabang for admin cabang
###
get http://localhost:5000/gettransaksicabang

###
get http://localhost:5000/gettransaksinotification/ORDER-1734016405945

###
delete http://localhost:5000/deletetransaksi/baaed04e-9987-4026-8997-08765f2f9869
###
get http://localhost:5000/rekapharianuser?tanggal=2024-12-04

###
get http://localhost:5000/rekapharianuser?tanggal=2024-12-19

###
put http://192.168.100.18:5000/updateuser/me/94e861b3-2af5-447a-91f5-bb285c6f7a3b
Content-Type: application/json

{
  "password":"12345",
  "confpassword":"12345"
}

###
post http://192.168.100.18:5000/createbarangcabang
Content-Type: application/json

{
  "baranguuid":"0dca2395-7e4e-437f-a46f-976d67691a43",
  "cabanguuid":"bb88b401-f02f-4ff9-8b7b-68826173eef7"
}

###
POST http://localhost:5000/createtransaksicabang
Content-Type: application/json

{
  "pembayaran": "cash",
  "items": [
    {
      "baranguuid": "08d4c3df-09d3-46a2-b841-80d825309151",
      "jumlahbarang": 20
    }
  ]
}

###
get http://localhost:5000/barangcabang

###
get http://localhost:5000/getusercabang

###
get http://localhost:5000/barangcabangsuperadmin


